### ISSUE TITLE
[feature request] programpad and turbo controller support

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Danjovic/Digi-Snes#1]
programpad and turbo controller support request

**Comment by Danjovic** [comment]
Thanks for the suggestions. 
I think it is possible to add turbo to the buttons that are held press during power up. As for the programmable feature that would require more buttons to the interface.

**Comment by Danjovic** [comment]
Added and tested Turbo function. As for programpad I will not add them due to the lack of extra buttons to become programmable.
