### ISSUE TITLE
NES fix

### ISSUE THREAD

**Issue by testoasarapida** [Danjovic/Digi-Snes#2]
Hey I know this is an old repo but recently I followed your project and used my Attiny85 to make my NES controller usable on PC. I loaded up your code and buttons 0, 1, 4, 5 were flashing continously (PC was detecting constant "pressing" of those buttons) even if they don't actually exist on the controller (B, A is 2, 3 and Start, Select are 6, 7). 

Now I'm a total noob at Arduino code and I won't pretend I fully understand what the code is doing, but I fixed it by commenting the lines 136 to 146. Nothing seems broken so far.

**Comment by Danjovic** [comment]
Original NES controllers will respond with LOW on the data line after the 8th clock bit. That will be interpreted as buttons held down and the code will try to auto-fire them. The solution for this problem involves differentiate a NES from a SNES controller. 
Thanks for the contribution.

**Comment by Danjovic** [comment]
Fixed the ghost autofired buttons with original NES controllers. Found and fixed another bug; the missing pullup on the DATA. As an extra feature I have unified the button mapping. Now A,B,Sel,Start on NES activates the same PC buttons as the SNES controllers (1,2,7,8 respectively).
